name: Cisbaf_NEP
description: EAD - Cisbaf.

publish_to: 'none'


version: 1.0.0+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_downloader: ^1.7.3
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  url_launcher: ^6.0.20
  flutter_inappwebview: ^5.3.2
  plugin_platform_interface: ^2.1.2
  flutter_custom_tabs: ^1.0.4
  restart_app: ^1.1.0
  webview_flutter: ^3.0.2
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  firebase_core: ^1.14.0
  overlay_support: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
  - images/logo.png
  - images/fundobranco.png